### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by caiosba** [Expensify/react-native-share-menu#1]
Right now it just works for Android.

**Comment by infojunkie** [comment]
This helps? https://github.com/facebook/react-native/issues/1626

**Comment by infojunkie** [comment]
https://github.com/andrewsardone/react-native-ios-share-extension

**Comment by caiosba** [comment]
Thanks to @ahmednasserswe, we support iOS now! :)

We still need to adapt the `example` to iOS, but Ahmed is working on that too.
