### ISSUE TITLE
After successfully installation of all steps Nothing happens when you click share from IOS device.

### ISSUE THREAD

**Issue by baxri** [Expensify/react-native-share-menu#103]
Hey, I did installation base on documentation for IOS and Android. Was  able to create successfull build and My app appears in share menu of the IOS device. but when I click on post button to share my text and image it does not appears my react native app with passed information.  How can I debug or what may be the problem.

```
{
   "react-native": "0.63.4"
}
```

![IMG_0723](https://user-images.githubusercontent.com/7827156/105627321-b6f6ff80-5e4f-11eb-9a56-8f253872055d.PNG)

**Comment by compelling** [comment]
Have the same problem. Set shareextention target xcode then look at logging in the console - or place some breakpoints in the Swift code of the plugin.
Xcode will ask what application to start before the extension - just select Safari. Then share eg a website to the extension. In my case everything looks fine, but we nevet got the share listener callback.
We ended up using our own share view and placed our code inside that. 
See https://github.com/meedan/react-native-share-menu/issues/96

**Comment by baxri** [comment]
This library is not maintained anymore?

**Comment by caiosba** [comment]
Does it happen on Android too?

**Comment by compelling** [comment]
Works fine in Android for us. Its just on iOS where you need to place your code in a custom share view, as the listener never gets called.

**Comment by baxri** [comment]
yeah nothing happens on IOS @caiosba

**Comment by raveracker** [comment]
Can you share the step by step process @baxri for setting up in iOS. I have managed to get it working on ios

**Comment by andrewkucz** [comment]
I had this problem and it was solved by following the updated instructions in [this PR](https://github.com/meedan/react-native-share-menu/pull/102) regarding the URL scheme in the info.plist file

You may need to make sure your URL schemes are set up correctly in the PList files. In one of the places the url scheme should include the `://` and in one of the places it should not. Hope this helps

**Comment by vishnuindrabalan** [comment]
Please check the `CFBundleURLSchemes`   in the App's Info.plist and the `HostAppURLScheme`  in ShareExtension's Info.plist.
**Example:**
**In App's Info.plist**
         `<key>CFBundleURLSchemes</key>
	<array>
		<string>com.yourappname.apps.2323323-323232-3</string>
	</array>`
	
**In ShareExtenstion's Info.plist**
        `<key>HostAppURLScheme</key>
	<string>com.yourappname.apps.2323323-323232-3://</string>`
	
	
	Also, ensure you don't have any other conflicting CFBundleURLSchemes in your app's Info.plist

**Comment by caiosba** [comment]
Fixed as per #96.

**Comment by dungdt-itealteam** [comment]
@compelling  can you help me? i got this problem and can not do any thing because data is not transfer to my app

**Comment by NTJ3** [comment]
I'm facing the same problem... 
@meedan Any solution?

**Comment by chanphillip** [comment]
I had the same issue until I saw this post.

My problem was `HostAppURLScheme` in **ShareExtenstion's Info.plist** missing `://` at the end
