### ISSUE TITLE
Change height of Share Extension View

### ISSUE THREAD

**Issue by harrysayers** [Expensify/react-native-share-menu#108]
Hi,

I was wondering how I would go about changing the height of the share extension view (The modal that appears once you've clicked your extension in the share menu)... I don't want to add things to the swift file as it'll get overwritten in a future version... Is there a way to do this? I want the view to be half the screen height.

- I'm using a custom IOS view (Following the instructions provided) 

Thanks very much,
Harry

**Comment by harrysayers** [comment]
I figured this out.... add a container view to your main extension storyboard then wrap your container view in a navigation controller.... make sure to add auto layout constraints to your container view and voila it should show like below :) 

<img width="360" alt="Screenshot 2021-03-01 at 16 26 01" src="https://user-images.githubusercontent.com/12693398/109526753-d286a300-7aaa-11eb-9fb1-f3f3560af194.png">

**Comment by MykolJames** [comment]
> I figured this out.... add a container view to your main extension storyboard then wrap your container view in a navigation controller.... make sure to add auto layout constraints to your container view and voila it should show like below :)
> 
> <img alt="Screenshot 2021-03-01 at 16 26 01" width="360" src="https://user-images.githubusercontent.com/12693398/109526753-d286a300-7aaa-11eb-9fb1-f3f3560af194.png">

Can you share on what the storyboard looks like? I'm also trying to change the height of the share extension.

**Comment by HugoGresse** [comment]
Also interested into more explanation for this... being not an iOS Developer this is not obvious...

**Comment by kemusa** [comment]
Another way to achieve this is to change the background color of the screen in your React Native application to be transparent and creating a view within it that has a smaller height. I'm using React Navigation so I achieved this by changing the backgroundColor of the Stack Navigator for my share extension. 

For the background color:
```   
import { createStackNavigator } from '@react-navigation/stack';
 
const { Navigator, Screen } = Stack;

<Navigator
      screenOptions={{
        headerShown: false,
        cardStyle: { backgroundColor: 'transparent' },
      }}>
... Your screens ...
</Navigator>`
```
Then the container view:
```
import React from 'react';
import { TouchableOpacity, View } from 'react-native';
import { ShareMenuReactView } from 'react-native-share-menu';
import styles from './styles';

const CollectionTemplate: React.FC<ShareExtensionContainerProps> = ({
  children,
}) => {
  const closeExtension = () => {
    ShareMenuReactView.dismissExtension();
  };
  return (
    <View style={styles.container}>
      <TouchableOpacity
        style={styles.background}
        onPress={closeExtension}></TouchableOpacity>
      <View style={styles.extension}>{children}</View>
    </View>
  );
};

export default CollectionTemplate;`
```

The wrapper styles: 
```
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  background: {
    backgroundColor: 'rgba(0,0,0,0.01)',
    flex: 1,
    height: 100,
    top: 0,
  },
  container: {
    flex: 1,
  },
  extension: {
    position: 'absolute',
    bottom: 0,
    height: '70%',
    width: '100%',
    borderRadius: 16,
    backgroundColor: '#fff',
  },
});

export default styles;
```

Then wrap each screen's views:
```
    <ShareExtensionContainer>
      ... Your screen's code ...
    </ShareExtensionContainer>
```
Which led to this outcome:

<img src="https://user-images.githubusercontent.com/12296084/134489869-657ea476-6e0d-4d8a-b1f5-d92e49aae146.png" width="250" />

Now you can get creative within the share extension! 🙌🏿

**Comment by Bayramito** [comment]
> I figured this out.... add a container view to your main extension storyboard then wrap your container view in a navigation controller.... make sure to add auto layout constraints to your container view and voila it should show like below :)
> 
> <img alt="Screenshot 2021-03-01 at 16 26 01" width="360" src="https://user-images.githubusercontent.com/12693398/109526753-d286a300-7aaa-11eb-9fb1-f3f3560af194.png">

can you explain it more please

**Comment by stoicaandrei** [comment]
This should do the trick

`ShareExtension/Info.plist`
```
<key>ReactShareViewBackgroundColor</key>
<dict>
	<key>Transparent</key>
	<true/>
</dict>
```

**Comment by kadiryaka** [comment]
> This should do the trick
> 
> `ShareExtension/Info.plist`
> 
> ```
> <key>ReactShareViewBackgroundColor</key>
> <dict>
> 	<key>Transparent</key>
> 	<true/>
> </dict>
> ```

Thanks @stoicaandrei 

And 

` 
return (
    <View style={styles.container}>
{/* UI render */}
    </View>
  );
`

`  
container: {
    position: 'absolute',
    bottom: 0,
    height: '50%',
    width: '100%',
    backgroundColor: 'white',
  },
`

<img width="401" alt="Screenshot 2023-11-27 at 18 10 00" src="https://github.com/Expensify/react-native-share-menu/assets/5338363/3cc0eb22-3fcc-47ce-89d7-25496c542352">

**Comment by skizzo** [comment]
Could someone please explain how to do this in XCode?

> I figured this out.... add a container view to your main extension storyboard then wrap your container view in a navigation controller.... make sure to add auto layout constraints to your container view and voila it should show like below :)


Simply adding 
```
<key>ReactShareViewBackgroundColor</key>
<dict>
   <key>Transparent</key>
   <true/>
</dict>
```
to `Info.plist` doesn't do the trick for me.
