### ISSUE TITLE
Sharing data between App and ShareExtension

### ISSUE THREAD

**Issue by quriosapien** [Expensify/react-native-share-menu#114]
I am using AsyncStorage in my App component to store some persistent data.
How can I access these in the Share Extension component ??

For example - I am saving the loggedIn user details using Async storage. I want to check whether user is loggedIn or not in the ShareExtension component.

**Comment by Shchepotin** [comment]
It's a limitation of AsyncStorage not ShareExtension, because AsyncStorage don't support [app groups](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_application-groups) for now. If you need you can implement your own AsyncStorage via [react-native-sqlite-storage](https://github.com/andpor/react-native-sqlite-storage) which [support](https://github.com/andpor/react-native-sqlite-storage#opening-a-database-in-an-app-groups-shared-container-ios) app groups.

**Comment by quriosapien** [comment]
@Shchepotin How about using Realm??

Also, if you can point me to any article or tutorial which can guide me to implement these, it would be really helpful!

**Comment by Shchepotin** [comment]
@ikmrgrv as far as I know Realm also not support app groups.

Install react-native-sqlite-storage and [configure app groups](https://github.com/andpor/react-native-sqlite-storage#opening-a-database-in-an-app-groups-shared-container-ios).

Basic implementation in TypeScript:

```ts
import SQLite from 'react-native-sqlite-storage';
SQLite.enablePromise(true);

class AsyncStorage {
  private static db: any;

  public static async openDatabase() {
    if (!AsyncStorage.db) {
      AsyncStorage.db = await SQLite.openDatabase({
        name: 'key-value.db',
        location: 'Shared',
      });

      await this.db.executeSql('CREATE TABLE IF NOT EXISTS keyValue (key text unique, value text)');
    }

    return AsyncStorage.db;
  }

  public static async getItem(key: string) {
    const db = await AsyncStorage.openDatabase();
    const [result] = await db.executeSql('SELECT value FROM keyValue WHERE key = ?', [key]);
    return result.rows.item(0)?.value;
  }

  public static async setItem(key: string, value: string) {
    const db = await AsyncStorage.openDatabase();
    await db.executeSql('REPLACE INTO keyValue (key, value) VALUES (?,?)', [key, value]);
  }

  public static async removeItem(key: string) {
    const db = await AsyncStorage.openDatabase();
    await db.executeSql('DELETE FROM keyValue WHERE key = ?', [key]);
  }
  
  // TODO: if need implement another methods from AsyncStorage
}

export default AsyncStorage;
```

Usage:

```ts
import AsyncStorage from 'path/to/custom/AsyncStorage';

await AsyncStorage.setItem('data', 'some data');

const data = await AsyncStorage.getItem('data');
```

**Comment by vstoyanoff** [comment]
I am using https://www.npmjs.com/package/react-native-shared-group-preferences. It works like charm and has the same API as AsynStorage. Generally is not a good idea to share large chunks of data so you can use this to share only what is needed.

**Comment by ikmrgrv** [comment]
@Shchepotin 
I get this error when I try to read item in the ShareMenu component.

[TypeError: null is not an object (evaluating 'NativeModules["SQLite"][method]')]

Do you know how can I resolve this ??

**Comment by tucka** [comment]
Thanks @vstoyanoff for your hint using react-native-shared-group-preferences.

This is working perfectly in the "main" application but not in the ShareExtension.

When calling `SharedGroupPreferences.setItem("savedData", userData, appGroupIdentifier)` I get the following Error:

> [TypeError: null is not an object (evaluating 'RNReactNativeSharedGroupPreferences.setItem')]

I'm using Expo (ejected) in the main application. Any idea what's going on?

Do you have an working example using react-native-share-menu together with react-native-shared-group-preferences?

Appreciate your support!
Thanks!
Tucka

**Comment by tucka** [comment]
I think I have found the solution. You have to add `RNReactNativeSharedGroupPreferences`' to the Podfile.
```
target 'ShareExtension' do
  use_react_native!

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  pod 'RNReactNativeSharedGroupPreferences', :path => '../node_modules/react-native-shared-group-preferences'
  # Manually link packages here to keep your extension bundle size minimal
end
```

**Comment by quriosapien** [comment]
Yes, somehow, for the ShareExtension, we need to manually link Storage Modules in PodFile.


Same for SQLite3 ...
Even when using RN 0.63+ version.

**Comment by vstoyanoff** [comment]
@tucka Very sorry for the late response. You need to add the `pod 'RNReactNativeSharedGroupPreferences', :path => '../node_modules/react-native-shared-group-preferences'` to the sharing menu target in the Podfile.

**Comment by quriosapien** [comment]
I finally used SQLite3 and it worked.
Thanks @Shchepotin for the help.
Also, @vstoyanoff suggested that `react-native-shared-group-preferences` works fine.

Closing this issue with the above mentioned resolutions.
Thanks :)
