### ISSUE TITLE
Usage in iOS

### ISSUE THREAD

**Issue by raminious** [Expensify/react-native-share-menu#12]
Your documentation about iOS installation is not clear for me.

> In the share extension loadView() method, add

Please tell me where is this loadView() function.
Also please update docs to compatible with newer version of React.

Thank you

**Comment by paulcollett** [comment]
+1. Would be very helpful!

**Comment by jln-dk** [comment]
https://github.com/meedan/react-native-share-menu/blob/master/example/ios/README.md

**Comment by infojunkie** [comment]
Thanks for the reply @jesperlndk - this link should provide the adequate info.
