### ISSUE TITLE
"undefined is not an object (evaluating 'ShareMenu.getSharedText')"

### ISSUE THREAD

**Issue by zethni** [Expensify/react-native-share-menu#13]
On my Android device, I can't avoid getting this error. I've used the sample code, reverted react-native as far back as 0.25.1, cleared npm caches, started from scratch, double-checked the various android-specific files, etc. If I remove the getSharedText call and just use canned text as sharedText state string, everything works fine. Any ideas where this is coming from?

**Comment by zethni** [comment]
Update - was eventually able to get this running on 0.25.1. Would love to see it work on newer versions of react native.

**Comment by Soleguia** [comment]
Hi! I'm totally new with React Native. 

I'm trying this on an **Android device** too and having the same issue, I think.

**_Cannot read property 'getSharedText' of undefined_**

I'm trying sharing from web browser but **ShareMenu** variable is undefined.

I don't understand what you, @zethni , have done

> If I remove the getSharedText call and just use canned text as sharedText state string, everything works fine.

Does it worked? Could you explain a little bit?

Thanks :D

**Comment by zethni** [comment]
@Soleguia 
I meant that I could get the share button from this app to show up in the share menu, but still couldn't use the actual share data. I commented out this part: 

>  `ShareMenu.getSharedText((text :string) => {
>       if (text && text.length) {
>         that.setState({ sharedText: text });
>       }
>     })`

And changed the state call in the constructor to:

> `this.state = {
>       sharedText: 'text text'
>     };`

So I could get the rest of the app to work, but it wasn't reading the shared text

Ultimately, I started from scratch with the [example](url), putting that folder into a folder and running `npm install`, which pulled the dependencies including the older version of react-native (0.25.1)

**Comment by Soleguia** [comment]
I've made a fresh installation yesterday and the only way to make it run with this was upgrading react-native to 0.33

Are you telling that share only works for 0.25 or lower??? O.o

:(

BTW: your "text text"-fix works fine xD

**Comment by zethni** [comment]
@Soleguia I may be missing something, but I couldn't get it to work on 0.33...

**Comment by caiosba** [comment]
Should be working with RN 0.33 yes, as per #8

**Comment by christianversloot** [comment]
One of the installation instructions is:

```new ShareMenuPackage(this)  // <------ add here```

I've seen things go wrong here. I know that I'm rather late, but what if you tried

```new ShareMenuPackage()  // <------ add here```

instead of the upper one, this made it work at various other packages

**Comment by caiosba** [comment]
I updated the documentation. It's basically what @christianversloot said. I just tried with latest React Native and it's working well.

**Comment by siddharthkp** [comment]
This doesn't seem to work with the [automatic installation method](https://github.com/meedan/react-native-share-menu#automatic-installation-react-native-036).

Getting the same error: `undefined is not an object (evaluating 'ShareMenu.getSharedText')`

**Comment by lukelu520** [comment]
The error shows up in web application. Maybe share menu doesn't work with web ?
Hope to hear your expertise to resolve it. (RN 0.64.3)
