### ISSUE TITLE
App not showing in share menu 

### ISSUE THREAD

**Issue by uplamartya** [Expensify/react-native-share-menu#138]
<img width="440" alt="Screenshot 2021-07-13 at 12 41 07 AM" src="https://user-images.githubusercontent.com/47631015/125342866-059f4400-e373-11eb-9461-dc03b297f2a5.png">

**### Info.plist from app -** 
[Info.plist.txt](https://github.com/meedan/react-native-share-menu/files/6803858/Info.plist.txt)

**### Info.plist from extension -** 
[Info2.plist.txt](https://github.com/meedan/react-native-share-menu/files/6803862/Info2.plist.txt)

**Comment by viktorRot** [comment]
@uplamartya Did you find a solution? I have same issue, that my app is not appearing in the share list.

**Comment by ghost** [comment]
@uplamartya @viktorRot  Did you find a solution? I have the same issue.
