### ISSUE TITLE
Receive share also when app is already running?

### ISSUE THREAD

**Issue by georgjaehnig** [Expensify/react-native-share-menu#18]
Hi, thanks for your module! It does work on my app – but only when the app was not started yet. If the app is already running in the background, nothing happens.

It's also kind of clear to me: `componentWillMount()` was already called, so there is no trigger at this point. But is there still a way to get this working, i.e. that I can share a (new) text even when my target app is already running?

Here's my current code:

    componentWillMount() {
      ShareMenu.getSharedText((text) => {
        console.log(text);
      });
    }

**Comment by caiosba** [comment]
Humm try this please:

`componentWillMount() {
  ShareMenu.getSharedText((text) => {
    console.log(text);
  });
}`

**Comment by caiosba** [comment]
Humm try this please:

`componentWillUpdate() {
  ShareMenu.getSharedText((text) => {
    console.log(text);
  });
}`

**Comment by georgjaehnig** [comment]
Unfortunately, using `componentWillUpdate()` doesn't help:

- On the one hand, it now gets triggered way too often, namely on any screen update, even if I just change a Picker value.
- On the other hand, still nothing happens when I call the share action from another app while my app is running.

Interestingly, even the following is the case:
- Let's say my app is not running and I share the text `foo` to my app. Then my app starts, and with the code in `componentWillUpdate()`, I see `foo` – as it should be.
- But now, if I share from the other app `bar`, at first nothing happens. Then, If I cause a component update (for instance by changing a Picker value), the text from `ShareMenu.getSharedText` is still `foo`.

I guess we must somehow tie this code to a event, no? Maybe according to [Linking](https://facebook.github.io/react-native/docs/linking.html), add an event listener, so that it's possible to write

    addEventListener('text', this._handleTextShare);

no?

BTW: I'm testing on Android 6.0.1.

**Comment by georgjaehnig** [comment]
So I could solve the problem for me with setting

        android:launchMode="singleTop"

within `AndroidManifest.xml`. Context:

      <activity
        android:name=".MainActivity"
        android:launchMode="singleTop"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
        ...

**Comment by caiosba** [comment]
I just fixed this on version 2.0.0. I basically had to implement `onNewIntent` on the module code. In my code I also had to implement some logic to get the latest intent when the app comes to foreground: https://github.com/meedan/check-mark/blob/150f88fb83f08d41a0530827d5a02a544859f3ed/index.js#L70-L110.
