### ISSUE TITLE
share image?

### ISSUE THREAD

**Issue by cbjs** [Expensify/react-native-share-menu#19]
is it possible for this package to share image

**Comment by caiosba** [comment]
There is a PR for that but I didn't review yet: https://github.com/meedan/react-native-share-menu/pull/17. Can you try it please?

**Comment by isaachinman** [comment]
@caiosba Any estimate for this functionality being merged? Also you'll see in #17 that multi-image sharing has also been added by other contributors.

**Comment by caiosba** [comment]
Yes, I'll try to do that until end of week.

**Comment by caiosba** [comment]
This feature is available now, starting on version 2.1.0.
