### ISSUE TITLE
Building offline bundle

### ISSUE THREAD

**Issue by dimapaloskin** [Expensify/react-native-share-menu#2]
Hello!

How I can build offline bundle of extension?
When I using the
`jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];`
I have follow error:

`[tid:com.facebook.react.JavaScript] Unable to execute JS call: __fbBatchedBridge is undefined
2016-06-09 11:27:55.913 [fatal]`

Thanks!

**Comment by dimapaloskin** [comment]
Resolved.

Need to share main.jsbundle via Target Memebership

**Comment by caiosba** [comment]
Thanks for documenting that here.
