### ISSUE TITLE
swift install instructions?

### ISSUE THREAD

**Issue by swyxio** [Expensify/react-native-share-menu#21]
these instructions <https://github.com/meedan/react-native-share-menu/blob/master/example/ios/README.md> are written for obj c. surprising considering swift is a thing and xcode 9 creates ShareViewController in swift. can we get an update please?

**Comment by infojunkie** [comment]
We are not working with Swift at the moment. We do welcome contributions, though, so feel free to submit a PR!

**Comment by swyxio** [comment]
haha i am definitely not there yet. thank you.
