### ISSUE TITLE
ShareMenuModule

### ISSUE THREAD

**Issue by swyxio** [Expensify/react-native-share-menu#22]
this example code doesnt work anymore.. any ideas?

![image](https://user-images.githubusercontent.com/6764957/30779260-e3db596c-a0b9-11e7-9ef1-c75c4705b774.png)

**Comment by caiosba** [comment]
We currently don't have an iOS maintainer for this module, but volunteers are welcome! :)

**Comment by ajith-ab** [comment]
use [react-native-file-share-intent](https://github.com/ajith-ab/react-native-file-share-intent/)

**Comment by Gustash** [comment]
@sw-yx I know this is an old issue, but is there any chance you can tell me if it's still applicable?

**Comment by Gustash** [comment]
@sw-yx could you just let me know if you closed this because you no longer use this package or if it's because you've found a solution? If the latter, could you share it here please?

**Comment by swyxio** [comment]
ah sorry i was rushing and didnt leave a proper response. closed bc no longer using this package , sorry never found a solution, i just abandoned that project
