### ISSUE TITLE
Module not receiving new shared data when app is open

### ISSUE THREAD

**Issue by raminious** [Expensify/react-native-share-menu#24]
I'm not sure it's a bug or not, but the module doesn't get new data when app is open and in background mode. let me tell you what I did.

```
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:screenOrientation="portrait"
        android:launchMode="singleTask"
      >
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
          <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
        </intent-filter>

        <intent-filter>
          <action android:name="android.intent.action.SEND" />
          <category android:name="android.intent.category.DEFAULT" />
          <data android:mimeType="text/plain" />
        </intent-filter>
      </activity>
```

the most important thing in above config is that app is running in singleTask mode. although I tested other launchModes as well.

```
class ApplicationContainer extends React.Component {
  constructor(props) {
    super(props)
  }

  componentDidMount() {
    AppState.addEventListener('change', this.stateListener.bind(this))
  }

  handleAppStateChange(nextState) {
      ShareMenu.getSharedText((text) => this.onNewSharedText(text))
  }

  onNewSharedText(text) {
    if (!text || text.length === 0) {
      return false
    }
    
    console.log(text) ---> Here it says text is blank

    ShareMenu.clearSharedText()
  }

  render() {
  }
}

```

As you see I used ShareMenu inside AppState change function. so when you open the app through sending a share link, or when it comes from background to active mode, I check for new shared text. it works perfect when app is closed, but when app is open and working in background , I can't get new shared text.

Unfortunately I'm not an android developer to help you but I think you should develop an intent listener or something similar for this reason. I checked Telegram (https://github.com/DrKLO/Telegram) source code but didn't understand how they are handling this situation.

thanks.

**Comment by caiosba** [comment]
Closing because it duplicates #18 - going to work over there.

**Comment by caiosba** [comment]
I just fixed this on version 2.0.0. I basically had to implement `onNewIntent` on the module code. In my code I also had to implement some logic to get the latest intent when the app comes to foreground: https://github.com/meedan/check-mark/blob/150f88fb83f08d41a0530827d5a02a544859f3ed/index.js#L70-L110.

**Comment by gcstr** [comment]
@caiosba, thank for the suggestion. But it's not working for me. Where did you implement `onNewIntent`?
  
Actually, not even the option `singleTop` is working for me. It stills open another instance of the application. I tried to use, `singleInstance` also, but it doesen't  update the shared content and throws the error below.

```
Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
getSharedText
    ShareMenuModule.java:35
invoke
    Method.java
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:761
```

**Comment by caiosba** [comment]
@gcstr - I didn't need to change my `AndroidManifest.xml` (https://github.com/meedan/check-mark/blob/feature/6459-react-native/android/app/src/main/AndroidManifest.xml). All I had to do was to implement the `onNewIntent` method on the module code (https://github.com/meedan/react-native-share-menu/commit/e12f98b9c6dd5dfa0c265ff853f72f9f1d0241e4). If you use version 2.0.0, it should work.

**Comment by gcstr** [comment]
@caiosba, It works... partially 😢 
If I use the back button to return to the previous application that first shared the content and share anything again, I get the shared content.
But if I switch to the other app using the home button, and share nothing happens.

Did you have the same problem?

**Comment by caiosba** [comment]
Yes, I solved it using `AppState`: https://github.com/meedan/check-mark/blob/150f88fb83f08d41a0530827d5a02a544859f3ed/index.js#L83-L96

**Comment by gcstr** [comment]
@caiosba, how do you prevent new shared content from creating new instances of the app? Every time I share something, a new instance of my app is created.

**Comment by caiosba** [comment]
Humm this is happening to me too. I expect that it can be solved by using `singleTop`. I will try later and let you know. If you reach something, please let me know too.

**Comment by gcstr** [comment]
Definitely. 
`singleTop` won't prevent from opening new instances. I could achieve it using `singleInstance` and `singleTask`. But when one of them are set, the following error is thrown:

```
Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
getSharedText
    ShareMenuModule.java:35
invoke
    Method.java
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:761
```

**Comment by gcstr** [comment]
@caiosba, since this issue is not directly related to multiple instances of the app being opened, I created another issue: https://github.com/meedan/react-native-share-menu/issues/25

**Comment by caiosba** [comment]
Great, thanks, let's continue from there.

**Comment by sahilpandya** [comment]
Hey,

I am facing same issue, I tried all the above solutions but not able to workaround.

**Comment by dotronglong** [comment]
I face same issue, I tried above solution but none of them is working, the only way to let it work is to kill the app before sharing

Update: `singleTop` works, however, it generates many events of `AppState`
