### ISSUE TITLE
Prevent sharing actions from creating new instances of the App

### ISSUE THREAD

**Issue by gcstr** [Expensify/react-native-share-menu#25]
On Android, when any other application uses the system share menu to open and send data to the Application, a new instance is created.

A common way to prevent it would be just forcing `singleInstance` or `singleTask` in `AndroidManifest.xml`:

```
<activity
...
android:launchMode="singleInstance"
...>
</activity>
```

But when this is set the following error is thrown:

```
Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
getSharedText
    ShareMenuModule.java:35
invoke
    Method.java
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:761
```

**Comment by alexpouliquen** [comment]
Add to your app android manifest:
`android:documentLaunchMode="never"`

For receiving data when app is open you need to add an Event Emitter to the module.

**Comment by caiosba** [comment]
I didn't look at it deeply again yet, but when I do, I will take a look at those two commits: https://github.com/pedroordep/react-native-share-menu/commit/156ab35e09f6e8e8ffd7a1f444341b2e537ed4aa and https://github.com/Minds/react-native-share-menu/commit/64bb761db4b74f184aac1f9c8ddb37202d8922fb... you can look at them too :)

**Comment by abnerfs** [comment]
> 
> 
> Add to your app android manifest:
> `android:documentLaunchMode="never"`
> 
> For receiving data when app is open you need to add an Event Emitter to the module.

That worked for me, thanks

**Comment by caiosba** [comment]
Thanks all, I updated the README.
