### ISSUE TITLE
Looking for an iOS developer to maintain the iOS version

### ISSUE THREAD

**Issue by caiosba** [Expensify/react-native-share-menu#27]
Hello friends,

We currently don't have anyone maintaining the iOS version. We're looking for a volunteer to maintain the iOS version.

**Comment by Saad-Bashar** [comment]
Did you get anyone @caiosba ??

**Comment by caiosba** [comment]
Not yet, @Saad-Bashar :(

**Comment by Saad-Bashar** [comment]
oh that's sad. I am actually using this package in one of my projects to share youtube video link from youtube app. It works okay in android. But could not make it work in iOS. I was having one issue with android. getSharedText is null. But saw today that someone fixed it so I also upgraded to latest version. Keep up the good work @caiosba  :)

**Comment by caiosba** [comment]
Thanks @Saad-Bashar !

**Comment by xD-saleem** [comment]
any update on any development on iOS? I want to use this package in order to share urls when clicking on the share menu. This currently works in android version. Please let me know if there is any alternative applications or even better technology which can be cross-platform to share menus. 

But good work on the android, works like a charm.

**Comment by caiosba** [comment]
No updates yet, @saleemadat :(
But thanks for your feedback on the Android version!

**Comment by NishidaRyu416** [comment]
https://github.com/alinz/react-native-share-extension

How about contacting them?
Their module even for ios doesn’t seem to work successfully. Also, they have the android version but it looks like they are only capable of maintaining the iOS version.

**Comment by ajith-ab** [comment]
@caiosba @NishidaRyu416 
https://github.com/ajith-ab/react-native-file-share-intent
 it's Good for Both Platforms

**Comment by Gustash** [comment]
Hey, I'm up for maintaining the iOS portion of this package. I've been looking to contribute to more OSS this year and this seems like an important project for a lot of people.

I have extensive experience with RN native modules for both iOS and Android, you can check my profile 🙂

**Comment by caiosba** [comment]
> Hey, I'm up for maintaining the iOS portion of this package. I've been looking to contribute to more OSS this year and this seems like an important project for a lot of people.
> 
> I have extensive experience with RN native modules for both iOS and Android, you can check my profile

Happy to hear it, @Gustash !! I can add you as a maintainer when you start hacking on it! Happy to answer any questions you have or if you need anything to start.

**Comment by Gustash** [comment]
@caiosba can you link me to the most pressing issues on iOS? It would probably be wise to start on those

**Comment by caiosba** [comment]
> @caiosba can you link me to the most pressing issues on iOS? It would probably be wise to start on those

Sure, I guess the most important one are #26 and #22 - basically bring it back to a working state and document in the README an example that works. I assigned you to both if you don't mind :)

**Comment by caiosba** [comment]
All iOS issues are labelled BTW: https://github.com/meedan/react-native-share-menu/labels/ios

**Comment by Gustash** [comment]
Thanks! I'll get to those first

**Comment by Gustash** [comment]
Btw @caiosba should I request your review for PRs related to iOS? I assume so since there were no iOS maintainers

**Comment by caiosba** [comment]
> Btw @caiosba should I request your review for PRs related to iOS? I assume so since there were no iOS maintainers

Just for sanity check, basically :D

**Comment by caiosba** [comment]
We found one! Thanks @Gustash !
