### ISSUE TITLE
callback of getSharedText doesn't call after upgrade version to 2.1.1

### ISSUE THREAD

**Issue by smnodame** [Expensify/react-native-share-menu#29]
Detail
Android version: 6.0
sdkVersion: 23

After I reversed the version back to 2.0.0, it works fine

**Comment by caiosba** [comment]
I just released a version 2.1.2 with PR #30 which probably solves this case. Also, before you upgrade, please try to remove your `.gradle` directory from your project. If you still have problems, please reopen.
