### ISSUE TITLE
Back to the host application

### ISSUE THREAD

**Issue by dimapaloskin** [Expensify/react-native-share-menu#3]
Hello.

How I can back to the host application from which occurred sharing?

Thanks.

**Comment by dimapaloskin** [comment]
Resolved for me, but I'm not sure that it's right way.

I modified ShareMenuModule.m this way:
`
static NSExtensionContext* extContext;  // new variable
`

and implement method which set extension context:

`
+(void) setContext: (NSExtensionContext*) context
{
  extContext = context;
}
`
also I added invokeToTheProxyApp bridge method:

`
RCT_EXPORT_METHOD(invokeToTheHostApp)
{
  [ extContext completeRequestReturningItems: @[] completionHandler: nil ];
}
`

ShareMenuModule.h:

`
+(void) setContext: (NSExtensionContext*) context; // new line
`

After I set up context in the ShareViewController.m:

`[ShareMenuModule setContext: self.extensionContext];`

Now I can use _NativeModules.ShareMenuModule.invokeToTheHostApp_ in the js application.

**Comment by caiosba** [comment]
Looks good. @ahmednasserswe, anything to add here?

**Comment by caiosba** [comment]
Can you please re-open this issue on https://github.com/meedan/react-native-share-menu ?

**Comment by dimapaloskin** [comment]
@caiosba Looks like I can't create issue for fork...

**Comment by caiosba** [comment]
Oh yes you're right... I asked the iOS maintainer to look at it :)

**Comment by caiosba** [comment]
Thanks!

**Comment by ahmednasserswe** [comment]
Thanks @dimapaloskin - merged your pull request - that is a great add :)
