### ISSUE TITLE
Handling shared link on Android

### ISSUE THREAD

**Issue by sixmoraltales** [Expensify/react-native-share-menu#32]
Thanks so much for sharing your work. It's a huge help.
I am however confused about how your React Native example code handles the shared link on Android. My question has two parts:

1. Is it necessary to handle the share within the main RN app itself? Or is it possible to do something like on iOS where the communication with the database can be executed from the Share Extension (java code?) without going through the main app? I am simply trying to share a URL directly to a firebase db, so I'm wondering if it's really necessary to bounce into the app after pressing the share icon in Android's share menu.

2. But if it is absolutely necessary to bounce into the app to execute the share to firebase, is there a best practice as to how to handle this? I noticed the default behaviour is to open the app at the root screen of the Navigation Stack. Is it possible to navigate directly to a particular screen of the app to handle the share to Firebase?

Thanks very much for any guidance you can provide in this murky and undocumented territory :)

**Comment by caiosba** [comment]
1. I don't think it's needed... you could write that code directly in the Java module if you want: https://github.com/meedan/react-native-share-menu/blob/master/android/src/main/java/com/meedan/ShareMenuModule.java#L43. But then you would need to fork the module and it would work only for your specific case.

2. I think you should be able to call this in any component: https://github.com/meedan/react-native-share-menu/blob/master/example/index.android.js#L25

**Comment by sixmoraltales** [comment]
Great. Thanks for the advice. 
Do you know if it's possible to bounce into the app at a particular screen in the Navigation Stack rather than at the root of the Navigation Stack?

**Comment by caiosba** [comment]
You should be able to do that with `react-navigation`, and navigate to a particular screen in the navigation stack when new shared text is received.

**Comment by sixmoraltales** [comment]
Forgive the silly question, but I can't figure out how to use your getSharedText function to detect when there is NO shared text. The callback only fires when the function successfully finds text (or image), but if not, it returns out of the function without returning anything. Is there something I am missing about your logic? Thanks again for the help.

**Comment by caiosba** [comment]
I'm not sure I understand the question... how are you able to "share nothing"?

**Comment by sixmoraltales** [comment]
Thanks a lot for the quick reply.

Apologies my question was unclear. Here's my use case: 
Every time the home screen loads, I want to check for shared text in case the user is coming into the app via the Android share url button in chrome (for example). My problem is that when there is no share activity detected, ShareMenu.getSharedText immediately escapes and doesn't execute the if/else condition. Here is the code I am using in componentDidMount() ...

`ShareMenu.getSharedText((text :string) => {
                            if (text && text.length) {
                                let comment = "empty comment"
                                var share = { link: text, comment: comment }
                                that.props.navigation.navigate ('AndroidShareScreen', { share: share })
                            } else {
                                //if no share detected, go to login screen 
                                that.props.navigation.navigate ('LoginScreen')
                            }
                        }) */`

 I noticed this line in your ShareMenuModul.java file which means the behaviour I noticed is by design: 
`if(mActivity == null) { return; }`

So, I'm wondering if it's possible to use your ShareMenu module to detect when there is NO share when the home screen loads (i.e. no intent, or activity)? Since getSharedText doesn't execute anything, or return anything when there is no intent detected, I can't figure out how to detect the case where there is NO shared text.

Thanks again!

**Comment by caiosba** [comment]
I suggest that you have the shared information in a state and populate the content there when there is shared content. When there isn't, the state will remain `null` and then you can go to the login screen when the state is `null`. Something like that below:

```
class Test extends Component {
  constructor(props) {
    super(props); 
    this.state = {
      sharedContent: null,
    }
  }

  componentWillMount() {
    ShareMenu.getSharedText((text :string) => {
      if (text && text.length) {
        this.setState({ sharedContent: text });
      }
    })
  }

  componentDidMount() {
    if (!this.state.sharedContent) {
      // no share detected
    }
  }
}
```

**Comment by sixmoraltales** [comment]
Ok great. Thanks for the confirmation. I was going to try that but worried that after a successful share the state of sharedContent would no longer be null, so I would then have to also check if it changes...

**Comment by caiosba** [comment]
Please reopen if you still have problems.
