### ISSUE TITLE
Execution failed for task ':react-native-share-menu:verifyReleaseResources'.

### ISSUE THREAD

**Issue by Jiwoopark0508** [Expensify/react-native-share-menu#33]
I am trying to build my app
I got this issue.

/Users/jiwoopark/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/8d9a7290a1492ddfdf79902ec2a56368/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.
    
/Users/jiwoopark/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/8d9a7290a1492ddfdf79902ec2a56368/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.
    
/Users/jiwoopark/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/8d9a7290a1492ddfdf79902ec2a56368/res/values-v26/values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
    
/Users/jiwoopark/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/8d9a7290a1492ddfdf79902ec2a56368/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontStyle not found.
    
/Users/jiwoopark/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/8d9a7290a1492ddfdf79902ec2a56368/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/font not found.
    
/Users/jiwoopark/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/8d9a7290a1492ddfdf79902ec2a56368/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontWeight not found.
    
Is cache issue?

**Comment by Jiwoopark0508** [comment]
Please help me I cannot find what is the issue

**Comment by Jiwoopark0508** [comment]
Execution failed for task ':react-native-share-menu:verifyReleaseResources'

**Comment by Jiwoopark0508** [comment]
It worked find in the debugging stage. But it starts to crack when I try to build release version.

**Comment by caiosba** [comment]
Does it work when you remove this module?

**Comment by Jiwoopark0508** [comment]
yes... I think it's a matter of gradle version. I solved it by ignite instead of react-native-cli. I think difference between them are build&sdk version.

**Comment by caiosba** [comment]
Great! Glad it worked.

**Comment by claudepark** [comment]
you should do like below  :)

in android/build.gradle

```
allprojects {
    ..............
    subprojects {
        afterEvaluate {
          project ->
            if (project.hasProperty("android")) {
                android {
                    compileSdkVersion = 27
                    buildToolsVersion = "27.0.3"
                }
            }
        }
    }
}
```

**Comment by lehi10** [comment]
This worked for me:
`./gradlew app:assembleRelease`
