### ISSUE TITLE
ShareMenuPackage is not abstract and does not override abstract method createJSModules

### ISSUE THREAD

**Issue by beshur** [Expensify/react-native-share-menu#34]
Hi.

Trying to run the example code from the Readme.
I did automatic installation with `react-native link` and then verified and added some missing pieces in MainActivity.java and AndroidManifest.xml.

Upon running `react-native run-android` I get this error:
```
[...]/node_modules/react-native-share-menu/android/src/main/java/com/meedan/ShareMenuPackage.java:15: error: ShareMenuPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class ShareMenuPackage implements ReactPackage {
       ^
1 error
:react-native-share-menu:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

```
    "react-native": "^0.39.0",
    "react-native-share-menu": "2.2.0"
```

What can I do here?
Thank you.

**Comment by caiosba** [comment]
Can you please try with a newer `react-native` version? Like 0.51 for example?

**Comment by beshur** [comment]
@caiosba, I have made a fix for myself, taking multiple posts like this as a proven _solution_

https://github.com/luggit/react-native-config/issues/154#issuecomment-338487947

**Comment by caiosba** [comment]
Nice, would be great to know if it's needed only for an older React Native version (like 0.39 for example). Did you see if it happens on React Native 0.51? I was not able to reproduce it. But many thinks for submitting this solution!

**Comment by beshur** [comment]
No, I did't verify it on 0.51.x as I had troubles with updating my app.
