### ISSUE TITLE
Sharing creates new instances AND single instance app not receiving shared URL

### ISSUE THREAD

**Issue by Technopathic** [Expensify/react-native-share-menu#39]
My issue is a combination of:
https://github.com/meedan/react-native-share-menu/issues/18
and
https://github.com/meedan/react-native-share-menu/issues/25

Running:
react-native: 0.59.9
react: 16.8.3
react-native-share-menu: 2.2.2

When I set:
```android:launchMode="singleTop"```

My app receives Shared URLs while the app is already running (desired effect), but it ends up creating multiple instances of my app (undesired effect). 

When I set the ```launchMode``` to ```"singleTask"``` or ```"singleInstance"```, my app does not receive Shared URLS while the app is already running (undesired effect), but also doesn't create multiple instances (desired effect). This is the case even when ShareMenu.getSharedText (see below) is in an AppState listener. 

Setting 
```android:documentLaunchMode="never"```

Also prevents my app from receiving Shared URLs while the app is currently running (undesired effect).

Is there a workaround for this? An alternative solution? 
```
componentWillMount() {
        AppState.addEventListener('change', this._handleAppStateChange);
}
_handleAppStateChange = (nextAppState) => {
        if (
          this.state.appState.match(/inactive|background/) &&
          nextAppState === 'active'
        ) {
            if(Platform.OS === 'android') {   
                ShareMenu.getSharedText((text) => {
                    if (text && text.length) {
                        if(text !== this.props.activeTab.site.url) {
                            this.setSite(text);
                        }
                    }
                })
            }
        }
        this.setState({appState: nextAppState});
};
```

**Comment by kartikpr** [comment]
@caiosba Any workaround to this ?
I thought this is similar to #18 and #24 and has been resolved ?

**Comment by rohit-ganapathy** [comment]
Hi even I was wondering if this issue has been resolved

**Comment by vinayakb-pits** [comment]
It's not working for me

**Comment by HemanthSurimani** [comment]
@Technopathic 

Is there any solution for this??

**Comment by sjonchhe** [comment]
Has this been solved yet?? Been stuck with this problem since a long time

**Comment by vaibhavhrt** [comment]
remove `android:launchMode`, i.e. use "standard" launchMode and add `android:documentLaunchMode="never"`. That will solve this problem.
But it will create another problem, app restarting(even if it's running) on click of FCM notification, still looking into how to fix that.

**Comment by AVATAR197** [comment]
@vaibhavhrt how it looks? Did you resolve the issue? Thanks for reply

**Comment by vaibhavhrt** [comment]
@AVATAR197 couldn't fix that, using a different library now.
[vaibhavhrt/rn-extensions-share ](https://github.com/vaibhavhrt/rn-extensions-share) which is a fork of [RocketChat/rn-extensions-share](https://github.com/RocketChat/rn-extensions-share) which is a fork of [alinz/react-native-share-extension](https://github.com/alinz/react-native-share-extension) which is no longer maintained.

**Comment by ajith-ab** [comment]
i ve used this package [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)

**Comment by infojunkie** [comment]
Hello @ajith-ab it looks that the package that you claim to be using is actually [your own creation](https://github.com/ajith-ab/react-native-receive-sharing-intent). Sounds like a disingenuous way to advertise for your module, by tagging every open issue here! It's also a pity you chose to create your own package from scratch, instead of contributing to an existing one.

**Comment by ajith-ab** [comment]
Hello @infojunkie I commented here due to this package cannot be updating by the Author and this package is only available for image and text. I have written package is Supports **file, image & text share receiving** . So here i will Commented here. I have created a package from scratch @infojunkie  please compare this two packages
