### ISSUE TITLE
How to render share UI only when dispatched by iOS Share Action and AndroidIntent?

### ISSUE THREAD

**Issue by allenrl** [Expensify/react-native-share-menu#4]
Hi, bit of a beginner here in RN, iOS and Android dev. The example code works quite well to demonstrate how the code behaves when the host app invokes the sharing action.

However, when loading the example app directly, index.ios.js and index.android.js will render an error because no sharing link/url has been passed to the app when NativeModules.ShareMenuModule.getSharedText is invoked inside componentWillMount.

In a real-world app, index.js would load the main app view and only when a sharing action is invoked by the host app and sent to the app would NativeModules.ShareMenuModule.getSharedText be invoked.

Any recommendations on how to accomplish this so NativeModules.ShareMenuModule.getSharedText is only invoked when sent to the app via the host app's sharing action?  I know this isn't really a question specifically about the module, but if you were even to just link me over to some resources explaining how to do this, that would suffice.  Being a n00b, I'm having a problem googling the right keywords to find a resource or tutorial to help learn this.

Thanks!
[PS, I wanted to post this to meedan/react-native-share-menu but there is no Issues tab so I posted here]

**Comment by caiosba** [comment]
Hi! There is an example here: https://github.com/meedan/generator-keefer/blob/master/test/src/android/index.js

Let me know if it works for you.

**Comment by allenrl** [comment]
Thanks, Caio.  I checked the example and it looks pretty similar to the one I followed on https://github.com/meedan/react-native-share-menu/blob/master/example/index.android.js
Android seems to run the getSharedText method fine even when it receives no url/text.

I think the problem I'm seeing is specific to the iOS implementation:  https://github.com/meedan/react-native-share-menu/blob/master/example/index.ios.js
It does not seem to fail gracefully: When you run the index.ios.js directly (in Xcode, execute run with Target = ExampleApp, NOT target = ShareExtension), no url/text is passed to it and I get an error like "undefined is not an object (evaluating '_ShareMenuModule.getSharedText')"

I think this error occurs when NativeModules.ShareMenuModule.getSharedText is invoked and in turn executes RCT_EXPORT_METHOD(getSharedText:(RCTResponseSenderBlock)callback) in ShareMenuModule.m

I don't know if this error is a bug?  I was thinking maybe I can avoid this error if I moved NativeModules.ShareMenuModule.getSharedText out of ComponentWillMount to somewhere else or if there is an event listener I can use so the app knows it came from a host app's sharing action?

**Comment by caiosba** [comment]
Glad that it's working for Android. Regarding iOS, I don't know... actually @ahmednasserswe is the maintainer of the iOS version :) Hopefully he can add something here.

Also, if you think that this approach can work, feel free to submit a PR.

**Comment by ahmednasserswe** [comment]
thanks @allenrl 
The component uses `NSExtensionContext` which is only available in an Application Extension.

**Comment by allenrl** [comment]
thanks for your reply @ahmednasserswe -- good to know this is not a bug 
So then, back to my original question:  Any recommendations on how to modify index.ios.js so NativeModules.ShareMenuModule.getSharedText is only invoked when sent to the app via the host app's sharing action? I know this isn't really a question specifically about the module, but if you were even to just link me over to some resources explaining how to do this, that would suffice. Being a n00b, I'm having a problem googling the right keywords to find a resource or tutorial to help learn this.  Is there some event listener or other trigger or state I can check in index.ios.js? Thanks!

**Comment by allenrl** [comment]
hi @ahmednasserswe, did you have any suggestions about what i can do about my question above?

> Any recommendations on how to modify index.ios.js so NativeModules.ShareMenuModule.getSharedText is only invoked when sent to the app via the host app's sharing action? I know this isn't really a question specifically about the module, but if you were even to just link me over to some resources explaining how to do this, that would suffice. Being a n00b, I'm having a problem googling the right keywords to find a resource or tutorial to help learn this. Is there some event listener or other trigger or state I can check in index.ios.js?

thanks so much for your help!

**Comment by caiosba** [comment]
I'm closing this issue and I will reopen it in the [Meedan repository](https://github.com/meedan/react-native-share-menu)

**Comment by caiosba** [comment]
Reopening... @ahmednasserswe reply here please.

**Comment by ahmednasserswe** [comment]
Apologies @allenrl for forgetting about the issue 

My idea is to treat the share extension as a combining app to the main app. I would suggest making another entry point to the share extension and handle its logic there. Name it `index_share_extension.ios.js` and separate it from the main app entry point `index.ios.js` 

^ I'll try this and update the repo accordingly

**Comment by caiosba** [comment]
We currently don't have an iOS maintainer for this module, but volunteers are welcome! :)

**Comment by ajith-ab** [comment]
i ve used this package [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)

**Comment by infojunkie** [comment]
Hello @ajith-ab it looks that the package that you claim to be using is actually [your own creation](https://github.com/ajith-ab/react-native-receive-sharing-intent). Sounds like a disingenuous way to advertise for your module, by tagging every open issue here! It's also a pity you chose to create your own package from scratch, instead of contributing to an existing one.

**Comment by ajith-ab** [comment]
Hello @infojunkie I commented here due to this package cannot be updating by the Author and this package is only available for image and text. I have written package is Supports **file, image & text share receiving** . So here i will Commented here. I have created a package from scratch @infojunkie  please compare this two packages

**Comment by Gustash** [comment]
@caiosba we need to rewrite the example project as it is quite out of date now. In terms of this issue in specific, one of the improvements I had in mind is to move to using listeners so that you don't need to check for a new shared item on app state change

**Comment by caiosba** [comment]
> using listeners so that you don't need to check for a new shared item on app state change

Nice, could it possibly fix #39 as well?

> we need to rewrite the example project as it is quite out of date now

Do you want to do this and then I test on Android, or vice-versa?

**Comment by Gustash** [comment]
> Nice, could it possibly fix #39 as well?

Yup, it most definitely would.

> Do you want to do this and then I test on Android, or vice-versa?

Yeah, I was about to get to it now. I can test on Android, no big deal, I know how to do Android dev too 🙂
