### ISSUE TITLE
Task :react-native-share-menu:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by sjonchhe** [Expensify/react-native-share-menu#40]
Whenever I try to build release build for android it throws an error. I am using React Native 0.60.5 on a windows.
It throws the following error:

Task :react-native-share-menu:verifyReleaseResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-share-menu:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.

**Comment by caiosba** [comment]
This error is not related to this module, but anyway... `android:style/TextAppearance.Material.Widget.Button.Borderless.Colored` was added in API 24 so you can't use it with version 23. You can use a style that was added before version 23.
