### ISSUE TITLE
"IN" animation 

### ISSUE THREAD

**Issue by caiosba** [Expensify/react-native-share-menu#5]
@dimapaloskin can you please re-submit your PR that adds this feature? I moved the repository and the PR was lost. Thanks!

**Comment by dimapaloskin** [comment]
@caiosba done.

**Comment by dimapaloskin** [comment]
@caiosba also, can you open issue in the js.coach and update repo url?

**Comment by caiosba** [comment]
Thanks! 

It's there already: https://js.coach/all/react-native-share-menu
