### ISSUE TITLE
Get Initial Share not a function

### ISSUE THREAD

**Issue by BraveEvidence** [Expensify/react-native-share-menu#52]
I am getting following error for iOS 
![Simulator Screen Shot - iPhone 11 - 2020-07-28 at 12 08 35](https://user-images.githubusercontent.com/24708929/88628129-135caa80-d0cb-11ea-87ee-d9615e42de36.png)

**Comment by Gustash** [comment]
The package here on GH isn't in sync with NPM yet. 

@caiosba can you close this issue when you make a new NPM release, please?

**Comment by BraveEvidence** [comment]
@Gustash Thanks for the response. Let me know once the package is in sync

**Comment by caiosba** [comment]
Fixed in 3.1.0.

**Comment by BraveEvidence** [comment]
Does this work in iOS simulator as well?

**Comment by Gustash** [comment]
> Does this work in iOS simulator as well?

Yes, as long as you followed the README instructions properly

**Comment by Gustash** [comment]
@PritishSawant also, I'm not sure why you're checking the platform. The JS API is the same for both platforms 🙂

**Comment by BraveEvidence** [comment]
@Gustash Actualy for android we have written something custom via native code
