### ISSUE TITLE
Execute the callback in the background (so without opening the interface)

### ISSUE THREAD

**Issue by NiccoloCase** [Expensify/react-native-share-menu#68]
I am new to using this module and after searching for a while I couldn't find a way to accomplish what I need. Did I miss something?

I would have this need: my application should show an interface if started normally, but if started via a share button (from another app) it should perform some tasks in the background without opening the application and hindering the user.
Thanks a lot in advance to everyone who will help me.

**Comment by Gustash** [comment]
This is not possible with React Native. If you want something like this it might be possible if you do it natively, but I'm not sure
