### ISSUE TITLE
Release mode

### ISSUE THREAD

**Issue by ftroitsky** [Expensify/react-native-share-menu#7]
Hello @ahmednasserswe do you have any tips for running it in release mode on a device?
I tried to use offline bundle by setting `jsCodeLocation` to `[[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];`
No luck. Main app can access this bundle but it looks like share extension fails to do it.

**Comment by ftroitsky** [comment]
Ok, It worked right after posting an issue)
Just cleaned and reseted everything and regenerated bundle with `react-native bundle --entry-file ./index.ios.js --platform ios --bundle-output ios/main.jsbundle` and made sure it's added in XCode project and Target Membership (#2) is set both for App and for ShareExt

**Comment by ahmednasserswe** [comment]
Thanks @ftroitsky for both reporting the issue and closing it :D

**Comment by ftroitsky** [comment]
You are welcome @ahmednasserswe :D! Sorry for bothering you. +5 to my Awareness... I tried this 3 times and it worked on 3d one.

**Comment by peteclark3** [comment]
@ftroitsky - Hey there... how can I ensure this target membership inclusion above (https://github.com/meedan/react-native-share-menu/issues/7#issuecomment-234941465) will happen when I archive the project for the App Store?
