### ISSUE TITLE
Null is not an object NativeModules.ShareMenuReactView.data Android Only

### ISSUE THREAD

**Issue by jempajarillo** [Expensify/react-native-share-menu#71]
I am new to react native coding and I need to implement a share sheet for ios and android side. 
The IOS version of the app using react-native-share-menu is working as expected but I am facing Null is not an object NativeModules.ShareMenuReactView.data  in android. 

Scenario:
1. Open chrome in android phone
2. Share any link to my test app
3. It will open the app and when I get the data using "ShareMenuReactView.data()" it returns the attached image.

I followed the instructions for Android installation except for the manual install part. 
React Native: 0.62

Please let me know what I'm missing here 

Here's my android manifest 
```
<activity
            android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:theme="@style/SplashScreen"
            android:windowSoftInputMode="adjustResize"
            android:exported="true"
            android:documentLaunchMode="never"
            >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="testapp" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="text/*" />
                <data android:mimeType="image/*" />
                <!-- Any other mime types you want to support -->
            </intent-filter>
        </activity>
```

<img width="390" alt="Screen Shot 2020-08-12 at 4 27 30 PM" src="https://user-images.githubusercontent.com/31024610/89993596-85331780-dcb9-11ea-823f-1b9818b953e1.png">

**Comment by Gustash** [comment]
`ShareMenuReactView` is only available for iOS. That module is for the custom RN share view which is only applicable to iOS. To get the share data you want to call `ShareMenu.getInitialShare` and you'll want to setup a listener with `ShareMenu.addNewShareListener`
