### ISSUE TITLE
Share Extension Crashes when sharing a screenshot

### ISSUE THREAD

**Issue by scottnash** [Expensify/react-native-share-menu#76]
When I try to share a screenshot on iPhone, the extension crashes as soon as a I call `ShareMenuReactView.data()`.  Works fine if I save the screenshot to photos and then share the photo from the photos app.  Is there a different way of handling screenshot shares, or is this a bug?

**Comment by scottnash** [comment]
To be clear, I mean when I try to share a screenshot from here

![Screen Shot 2020-08-26 at 11 21 43 AM](https://user-images.githubusercontent.com/984579/91322966-53788100-e78e-11ea-90ed-01f9d46c22e0.png)

**Comment by dabakovich** [comment]
@scottnash Did you found any solutions here? Facing the same issue.
@Gustash maybe you have any ideas what can brokes here?

**Comment by dabakovich** [comment]
@caiosba, @Gustash I'm getting the error messages in the console when trying to share a screenshot. It works fine for other types of data.

`Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file RNShareMenu/ShareMenuReactView.swift, line 126`

`SLComposeServiceViewController got NSURL (null) for public.image error: Error Domain=NSItemProviderErrorDomain Code=-1100 "Cannot load an object of class NSURL" UserInfo={NSLocalizedDescription=Cannot load an object of class NSURL}`

**Comment by dabakovich** [comment]
@scottnash
Just made a fork that fixes this issue. Due to the [answer](https://stackoverflow.com/a/46214026/7511217), the problem is that just after making a screenshot the image still not stored anywhere, so it's doesn't have any URL. So I'm storing it into a temporary folder (as described [here](https://stackoverflow.com/a/35240822/7511217)) and then providing the link to the share extension app.

https://github.com/dabakovich/react-native-share-menu

**Comment by caiosba** [comment]
Very cool, @dabakovich, thanks ! Are you planning to submit a PR?

**Comment by dabakovich** [comment]
Thanks, @caiosba. Yes, I can if it makes sense. But it would be great to gracefully review my code and test the extension behaviour because that was my first experiences in Swift.

**Comment by caiosba** [comment]
Yeah, we can review the PR and test it before merging. Thanks! :)

**Comment by m-zaink** [comment]
That crash still isn't fix @caiosba!
I do get the URL but it won't work once I navigate to app by means of

```js
ShareMenuReactView.continueInApp({
      data: data,
      mimeType: mimeType,
});
```

What ought to be done?

**Comment by m-zaink** [comment]
```
guard let url = data as? URL else {
  self.exit(withError: COULD_NOT_FIND_IMG_ERROR)
  return
}
```


This is where the problem seems to be occuring. 
Under `ShareMenuReactView.swift`, you aren't updating the imageProvider with the latest URL. Please update that.

**Comment by asadd-irfan** [comment]
please help... kindly explain i am trying to send data in my app from share by using continueInApp but i can't receive that data in my app. can anyone please help. @m-zaink  @caiosba @dabakovich @scottnash 

```
ShareMenuReactView.data().then(item => {
     ShareMenuReactView.continueInApp({
       anykey:"anyValue",
       data: item.data[0].data,
       mimeType: item.data[0].mimeType,
     });
   
   });
```

**Comment by Larens94** [comment]
I always have this problem:

version: "react-native-share-menu": "^6.0.0",

When I try to share a screenshot the application doesn't open.

how can I solve this problem?

**Comment by JesusTectronic** [comment]
In the `ShareMenuReactView` class, I noticed a variable name inconsistency in the `extractDataFromContext` function.

The issue is in this block of code:

```swift
let imageData: Data! = image.pngData();

// Creating a temporary URL for image data (UIImage)
guard let imageURL = NSURL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("TemporaryScreenshot.png") else {
  return
}

do {
  // Writing the image to the URL
  try imageData.write(to: imageURL)

  results.append([DATA_KEY: imageUrl.absoluteString, MIME_TYPE_KEY: imageURL.extractMimeType()])
} catch {
  callback(nil, NSException(name: NSExceptionName(rawValue: "Error"), reason:"Can't load image", userInfo:nil))
}
```

The temporary variable defined for "TemporaryScreenshot.png" is imageURL, but it is incorrectly used as imageUrl here:
```swift
results.append([DATA_KEY: imageUrl.absoluteString, MIME_TYPE_KEY: imageURL.extractMimeType()])
```

To fix this issue, you should change it to:
```swift
results.append([DATA_KEY: imageURL.absoluteString, MIME_TYPE_KEY: imageURL.extractMimeType()])
```


Add this in your `ShareViewController` in the `storeFile` function
[ShareViewController](https://github.com/Expensify/react-native-share-menu/issues/251#issuecomment-1666244369)

```swift
if let uiImage = data as? UIImage {
  let fileExtension = "png"
  let fileName = UUID().uuidString
  let filePath = groupFileManagerContainer
                  .appendingPathComponent("\(fileName).\(fileExtension)")
        
  guard let rawData: Data = uiImage.pngData() else {
     self.exit(withError: "Error while getting raw data")
     return
  }
        
  guard FileManager.default.createFile(atPath: filePath.path, contents: rawData) else {
      self.exit(withError: "Error while createFile")
      return
  }
        
  self.sharedItems.append([DATA_KEY: filePath.absoluteString, MIME_TYPE_KEY: "image/png"])
  semaphore.signal()
  return
}
```
