### ISSUE TITLE
Support for RN > 0.29

### ISSUE THREAD

**Issue by goodhyun** [Expensify/react-native-share-menu#8]
looks like we can't receive the instance of activity any more ? 

```
MainApplication.java:37: error: incompatible types: <anonymous ReactNativeHost> cannot be converted to Activity
            new ShareMenuPackage(this)  // <------ add here
                                 ^
```

please refer to [this](https://github.com/facebook/react-native/commit/dcc2abc1f63f91e53bf01f4bc56c5b7c76300617)

**Comment by blowupshappen** [comment]
I ran into this problem too. I haven't finished implementing the sharing, but I was able to get it to build, and my app shows up when sharing from other applications. Here are the files with the modifications I made (let me know if you notice I did anything dumb)

[react-native-share-menu.zip](https://github.com/meedan/react-native-share-menu/files/472051/react-native-share-menu.zip)

**Comment by caiosba** [comment]
I didn't try with RN > 0.29 yet. @blowupshappen , if you are able to finish and make it work, could you please submit a PR? :)

**Comment by goodhyun** [comment]
@blowupshappen it works like a charm. coincidentally, i was patching the code myself, but I missed the build.gradle and `getCurrentActivity()` wasn't accepted. 
`dependencies {
    compile 'com.facebook.react:react-native:0.33.+'
}`
Thanks again for the tip, and you better sent a PR with this.
