### ISSUE TITLE
Trying to setup but RNShareMenu.modulemap and SwiftShims not found.

### ISSUE THREAD

**Issue by andrewwongucsd** [Expensify/react-native-share-menu#86]
I tried to build on Xcode, then I received the following errors.
`<unknown>:0: error: module map file '/Users/xxxxxxxx/Library/Developer/Xcode/DerivedData/xxxxxxxx-dtmrmeyardwqggbmtswgztsrxkoc/Build/Products/Debug-iphonesimulator/RNShareMenu/RNShareMenu.modulemap' not found
<unknown>:0: error: module map file '/Users/xxxxxxxx/Library/Developer/Xcode/DerivedData/xxxxxxxx-dtmrmeyardwqggbmtswgztsrxkoc/Build/Products/Debug-iphonesimulator/RNShareMenu/RNShareMenu.modulemap' not found
<unknown>:0: error: missing required module 'SwiftShims'`

I ran `npx react-native run-ios` on terminal, then I got the following errors.
`warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'CocoaLibEvent' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'OpenSSL-Universal' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'YogaKit' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Flipper' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/xxxxxxxx/Documents/iOS/xxxxxxxx/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/xxxxxxxx/Documents/iOS/xxxxxxxx/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/xxxxxxxx/Documents/iOS/xxxxxxxx/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Flipper-PeerTalk' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Flipper-Folly' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Flipper-DoubleConversion' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 5.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'CocoaAsyncSocket' from project 'Pods')

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/xxxxxxxx/Library/Developer/Xcode/DerivedData/xxxxxxxx-apynuuqleozmmqcpopftawjpttds/Build/Intermediates.noindex/xxxxxxxx.build/Debug-iphonesimulator/xxxxxxxx.build/Objects-normal/x86_64/AppDelegate.o /Users/xxxxxxxx/Documents/iOS/xxxxxxxx/ios/xxxxxxxx/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
`

Please help me on this. Thanks in advance.

**Comment by andrewwongucsd** [comment]
I found out why it happened, but then another issue shows up.

**Comment by dungdt-itealteam** [comment]
@andrewwongucsd  can you tell me what problem and how to fix RNShareMenu.modulemap' not found issuess?
