### ISSUE TITLE
Works good in debug mode but not in release mode in iOS

### ISSUE THREAD

**Issue by sindu12jun** [Expensify/react-native-share-menu#87]
Hi, I follow all the instructions in iOS, I have set a custom view, it works good in debug mode, but in release mode, the screen freezes when I try to share an image, could you give me some clue on how to fix that?

**Comment by wanderbon** [comment]
Did you find solution?

**Comment by yungbigos** [comment]
Hi @sindu12jun, did you solve this? :)
