### ISSUE TITLE
No Data Transfer After Changing the Bundle Identifier

### ISSUE THREAD

**Issue by automationist** [Expensify/react-native-share-menu#93]
Hello, first of all, thanks for this module!

I started with the example project, and everything works fine, until I update the bundle identifiers (github.meedan.... stuff). The app properly shows the share view, but when I click Continue In App or Continue In App With Extra Data, no data is transferred. It seems that the callback function doesn't even get called.  

I updated the bundle identifier and app groups in General and Signing and Capabilities in both "Test" and "Share Extension" and also updated the HostAppBundleIdentifier. But I left the "ShareMenuModule" and "ShareMenuModule://" in the info.plist files. 

What could I possibly be doing wrong? I would appreciate any help. 

I do get this error when I run `yarn react-native run-ios`

> error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
>  - react-native-share-menu (to unlink run: "react-native unlink react-native-share-menu")
> This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.

**Comment by TuyenNguyenVan** [comment]
same issue

**Comment by automationist** [comment]
My issue was that the ios/ShareExtension/ShareExtension.entitlements file had the wrong group name different from what I set on Xcode.
