### ISSUE TITLE
IOS - On Share how to call the main logic written in App.js of the Main App

### ISSUE THREAD

**Issue by ashwanimm** [Expensify/react-native-share-menu#96]
"react-native": "0.63.3"
"react-native-share-menu": "^5.0.2"

Hi  @Gustash, I am facing issue with the share functionality in IOS. I followed the instructions (https://github.com/meedan/react-native-share-menu/blob/master/IOS_INSTRUCTIONS.md). While sharing, a popup comes with shared url but on clicking 'Post' button the popup goes away but not sure what's happening.

In the example Usage you have given nice way to listen to the shared data and take action on it. That works for Android.

Our requirement is that when User share we need to check and retrieve the auth-token (that User receives on login and stored on AsyncStorage). The shared data and the auth-token is then sent via API to the Server. This logic has been written in the App.js of the main App. For Android it works fine. But for IOS I am not able to figure out that how to call the App.js and pass the shared url.

Share is one of the main functionality of our App. Please can you help to fix this issue. 

Thanks in advance.

**Comment by compelling** [comment]
Hi @Gustash, same problem here. Have added some logging that goes to my server as console logging does not seem to work when the app is in the background. I see logging on the server when my app starts up, but nothing is logged when the handleShare function is supposed to be called. 

Scenario: I try is to share a URL from Safari in the simulator, then the std share window appears and I press Post. Then nothing more happens, it is as if the registered callbacks do not have effect.

Code snippet: 
class App extends React.Component {

  handleShare = (item) => {
    if (!item) return;
    server.addLog(item);
  }
  
  componentDidMount() {
    SplashScreen.hide();
    server.addLog("app started");
    ShareMenu.getInitialShare(this.handleShare);
    ShareMenu.addNewShareListener(this.handleShare);
  }

I have a bunch of other libs in the app, e.g. react-navigation - maybe share-menu has a known problem with one of those - would be good to know..
Anyone else with this problem on iOS, or an idea of how to fix?

**Comment by compelling** [comment]
Just shipped our app Grosh in a new version that uses the share-menu plugin. We simply could not get any calls through to the share listener in App.js for iOS. Instead we opted to use our own share view on iOS and placed our iOS code in that. For Android, share-menu works well and just as documented, and the sharelistener in App.js gets invoked as it should.

**Comment by vishnuindrabalan** [comment]
> "react-native": "0.63.3"
> "react-native-share-menu": "^5.0.2"
> 
> Hi @Gustash, I am facing issue with the share functionality in IOS. I followed the instructions (https://github.com/meedan/react-native-share-menu/blob/master/IOS_INSTRUCTIONS.md). While sharing, a popup comes with shared url but on clicking 'Post' button the popup goes away but not sure what's happening.
> 
> In the example Usage you have given nice way to listen to the shared data and take action on it. That works for Android.
> 
> Our requirement is that when User share we need to check and retrieve the auth-token (that User receives on login and stored on AsyncStorage). The shared data and the auth-token is then sent via API to the Server. This logic has been written in the App.js of the main App. For Android it works fine. But for IOS I am not able to figure out that how to call the App.js and pass the shared url.
> 
> Share is one of the main functionality of our App. Please can you help to fix this issue.
> 
> Thanks in advance.

Please check the `CFBundleURLSchemes`  you mentioned in the App's Info.plist and the `HostAppURLScheme` ShareExtension's Info.plist.
Example:
**In App's Info.plist** 
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				**<string>com.yourappname.apps.2323323-323232-3</string>**
			</array>
		</dict>
	</array>
	
	In ShareExtenstion's Info.plist
        <key>HostAppURLScheme</key>
	**<string>com.yourappname.apps.2323323-323232-3_://_</string>**
	
	Also, verify you don't have any other conflicting CFBundleURLSchemes in your app's Info.plist

**Comment by vishnuindrabalan** [comment]
Please check the `CFBundleURLSchemes`   in the App's Info.plist and the `HostAppURLScheme`  in ShareExtension's Info.plist.
**Example:**
**In App's Info.plist**
         `<key>CFBundleURLSchemes</key>
	<array>
		<string>com.yourappname.apps.2323323-323232-3</string>
	</array>`
	
**In ShareExtenstion's Info.plist**
        `<key>HostAppURLScheme</key>
	<string>com.yourappname.apps.2323323-323232-3://</string>`
	
	
	Also, ensure you don't have any other conflicting CFBundleURLSchemes in your app's Info.plist

**Comment by compelling** [comment]
Problem solved by the updated documentation as explained in this (duplicate) issue: https://github.com/meedan/react-native-share-menu/issues/103 Now we get the app called on iOS just like for Android :) Not quite worked out how to avoid the share dialog that appears on iOS before we open the app, make an empty custom share view just makes the thing crash after a one invocation. Would rather just handle the share action inside the react native code solely (that works on Android), but I guess that's how it is.

**Comment by caiosba** [comment]
Thanks! @compelling , is the updated documentation looking good in the README? If there is anything else to be added, feel free to submit a PR. If the current README looks good, I'll just close this issue.

**Comment by compelling** [comment]
Looks good to me, think you can close both issues (this and 103)

**Comment by caiosba** [comment]
Thanks!
